### ISSUE TITLE
Wrong Variable used

### ISSUE THREAD

**Issue by iainhamilton** [dexiio/dexi-php-client#6]
In file : dexi-php-client/src/Dexi/Runs.php

The below `$state` line 
```
public function getLatestResult($runId, $format = 'json', $state = null) {
        $format = in_array($format, array('json', 'xml', 'csv', 'scsv')) ? $format : 'json';
        $state = in_array($format, array('QUEUED', 'PENDING', 'RUNNING', 'FAILED', 'STOPPED', 'OK')) ? $state : '';
        return $this->client->requestJson("runs/$runId/latest/result?format=$format&state=$state");
```

should be:

```
$state = in_array($format, array('QUEUED', 'PENDING', 'RUNNING', 'FAILED', 'STOPPED', 'OK')) ? $state : '';
```

**Comment by iainhamilton** [comment]
Aw jeezzz...I meant

```$state = in_array($state, array('QUEUED', 'PENDING', 'RUNNING', 'FAILED', 'STOPPED', 'OK')) ? $state : '';```

**Comment by hofmeister** [comment]
Hi @iainhamilton - thanks for reporting this - we'll get it sorted but you're also more than welcome to open up a pull request for it.

**Comment by hofmeister** [comment]
Is fixed here: 
https://github.com/dexiio/dexi-php-client/commit/41ed79b57d7513bd5287638b308e89629daf208a
