### ISSUE TITLE
Incorrect return type in phpdoc for `Dexi\Runs::getLatestResult()`

### ISSUE THREAD

**Issue by RichAtPowderBlue** [dexiio/dexi-php-client#8]
`Dexi::runs->getLatestResult()` returns a `stdClass` object, but the phpdoc states that it returns a `Dexi\DTO\ResultDTO` (which I assume is the intended behaviour).

**Comment by andresangulo** [comment]
Hi - it is intended to return a model of type ResultDTO. We tried casting but figured it was unnecessary as the ResultDTO class doesn't have any methods or anything of use, so the return type is left there more as an aid when autocompleting and for documentation purposes. Is it giving you any issues?

**Comment by RichAtPowderBlue** [comment]
Hi, the only issue is that we like to type-hint, and I have a method which returns the result, which it can get using different methods (in dev we use `getLatestResult()`, whereas in prod we use `executeSync()`.

I can't type-hint because the return type for my method has to be `mixed`.

So basically, no not an issue any more as I can work around it, but it did cause some confusion when I had to work out why I wasn't receiving an object of the type indicated in the phpdoc.

I don't mind either way whether you fix it - I just thought you may want to as it would save confusion for others in future :)

**Comment by andresangulo** [comment]
Thank you for reporting this! I'll add it to our backlog to make sure we return the proper class type in the future
