### ISSUE TITLE
Incorrect namespace

### ISSUE THREAD

**Issue by danbettles** [dexiio/dexi-php-client#9]
Morning,

Firstly, thank you for your library.

The following namespace declaration is incorrect.  I think it should be `namespace Dexi\DTO;`.  

https://github.com/dexiio/dexi-php-client/blob/3d32ab8ba3ec272c75e58c9660aad50290bc8e5a/src/Dexi/DTO/DataSetRowSetDTO.php#L3

I spotted the problem because a warning is thrown by Composer when creating an optimised autoloader.

Many thanks,
Dan

**Comment by mortengf** [comment]
Hi Dan

Thank you for reporting this. I believe you are correct. We will get this
fixed in the near future and let you know once fixed.

Thank you for using Dexi :)

Best,
Morten

**Comment by ylovits** [comment]
Hello @danbettles,

The issue in now resolved.
Update the version in your composer.json and you are good to go
Thanks again for reporting this

Regards,
Michail

**Comment by danbettles** [comment]
Many thanks 👍
